sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_away
    username: root
    password: 962464
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    bucketName: xiaopy-store
  redis:
    host: localhost
    port: 6379
    password: 962464
    database: 0
  wechat:
    appid: wx86d9d1be24d2d5c2
    secret: 708b9383966b5f93ef17ea2a67febdb0
